### ISSUE TITLE
The iOS version won't be accepted by appstore.

### ISSUE THREAD

**Issue by OGFris** [Jelomite/twist-native#4]
I just wanted to point out that you'll probably have issues when trying to push it to appstore, because their rules state that webview apps are not accepted and react native might trigger it.

**Comment by Jelomite** [comment]
Thanks for the notice. As you've already saw, I'm not using a webview, I'm rebuilding the UI from scratch. Is there a specific code or dependency that you see as faulty, or do you think there might be a problem later on?

**Comment by OGFris** [comment]
Not really, I've not actually read all the codes but I just warned you that even react-native might be flagged by the appstore.

**Comment by Jelomite** [comment]
I see, thanks. I'll keep track of that
